"""Perceptual hash (pHash) implementation for video and images.

Compatible with Stash-box / goimagehash (Lee 1984 DCT-II perceptual hash):
- 25 frames sampled uniformly across 5% to 95% of video duration.
- Scaled to width 160 maintaining aspect ratio.
- Arranged in 5x5 sprite grid.
- Resized to 64x64 bilinear, converted to grayscale.
- 2D unscaled DCT-II computed using precomputed cosine matrix.
- Top-left 8x8 low frequency coefficients extracted.
- 64-bit hash generated by comparing against median (val > median).
"""

from __future__ import annotations

import logging
import time
from pathlib import Path

import numpy as np
from PIL import Image

from ..models.log_buffer import LogBuffer

logger = logging.getLogger(__name__)

# Precompute 64x64 cosine matrix for unscaled DCT-II (Lee 1984 / goimagehash)
# C(k, n) = cos((pi * (2*n + 1) * k) / (2 * N))
_N = 64
_n = np.arange(_N)
_k = np.arange(_N)
_COS_64 = np.cos(np.pi * np.outer(_k, 2 * _n + 1) / (2 * _N))
_COS_64_T = _COS_64.T


def compute_phash_from_image(image: Image.Image) -> str:
    """Compute 64-bit perceptual hash compatible with goimagehash / Stash-box.

    Args:
        image: PIL Image instance (e.g. video collage sprite).

    Returns:
        16-character lowercase hexadecimal hash string.
    """
    resized = image.resize((64, 64), Image.Resampling.BILINEAR)
    gray = resized.convert("L")
    pixels = np.array(gray, dtype=np.float64)

    # 2D unscaled DCT-II
    dct = _COS_64 @ pixels @ _COS_64_T

    # Extract top-left 8x8 coefficients
    block8x8 = dct[:8, :8]
    flat = block8x8.flatten()

    # Median of 64 coefficients (index 32 of sorted array, matching goimagehash)
    sorted_vals = np.sort(flat)
    median = sorted_vals[32]

    # Generate 64-bit hash
    hash_bits = 0
    for idx, val in enumerate(flat):
        if val > median:
            hash_bits |= 1 << (63 - idx)

    return f"{hash_bits:016x}"


def compute_video_phash(video_path: str | Path) -> str | None:
    """Compute perceptual video hash (pHash) compatible with Stash-box.

    Extracts 25 frames across the video, builds a 5x5 collage, and computes
    the 64-bit DCT perceptual hash.

    Args:
        video_path: Path to the video file.

    Returns:
        16-character lowercase hexadecimal hash string, or None if extraction fails.
    """
    path = Path(video_path)
    if not path.is_file():
        logger.warning(f"pHash 计算失败，文件不存在: {path}")
        return None

    try:
        import av
    except ImportError:
        logger.warning("未安装 PyAV (av)，无法计算视频 pHash")
        LogBuffer.log().write("\n ⚠️ [pHash识别] 未安装 PyAV (av) 视频解码库，无法提取视频指纹")
        return None

    try:
        with av.open(str(path)) as container:
            if not container.streams.video:
                logger.warning(f"视频无视频流: {path}")
                return None

            stream = container.streams.video[0]
            if stream.duration and stream.time_base:
                duration_sec = float(stream.duration * stream.time_base)
            elif container.duration:
                duration_sec = float(container.duration / 1_000_000)
            else:
                logger.warning(f"无法获取视频时长: {path}")
                return None

            if duration_sec < 1.0:
                logger.warning(f"视频时长过短 ({duration_sec}s): {path}")
                return None

            offset = 0.05 * duration_sec
            step = (0.90 * duration_sec) / 25
            timestamps = [offset + i * step for i in range(25)]

            frames: list[Image.Image] = []
            for i, ts in enumerate(timestamps):
                if stream.time_base:
                    pts = int(ts / stream.time_base)
                else:
                    pts = int(ts * 1000)
                container.seek(pts, stream=stream, backward=True)
                for packet in container.demux(stream):
                    for frame in packet.decode():
                        img = frame.to_image()
                        target_w = 160
                        target_h = max(1, int(img.height * (target_w / img.width)))
                        img_small = img.resize((target_w, target_h), Image.Resampling.BILINEAR)
                        frames.append(img_small)
                        break
                    if len(frames) == i + 1:
                        break

            if not frames:
                logger.warning(f"未能从视频中解码出任何画面: {path}")
                return None

            # Pad with last frame if slightly fewer than 25 frames were decoded
            while len(frames) < 25:
                frames.append(frames[-1])

            tile_w = 160
            tile_h = frames[0].height

            # Assemble 5x5 sprite
            sprite = Image.new("RGB", (tile_w * 5, tile_h * 5), color=(0, 0, 0))
            for idx, frame in enumerate(frames[:25]):
                col = idx % 5
                row = idx // 5
                sprite.paste(frame, (col * tile_w, row * tile_h))

            return compute_phash_from_image(sprite)

    except Exception as e:
        logger.warning(f"计算视频 pHash 异常: {e}", exc_info=True)
        return None


# Module-level scene cache: file_path -> scene dict
_PHASH_SCENE_CACHE: dict[str, dict] = {}


def get_cached_scene(video_path: str | Path) -> dict | None:
    """Get cached scene matching the video path."""
    try:
        return _PHASH_SCENE_CACHE.get(str(Path(video_path).resolve()))
    except Exception:
        return None


def set_cached_scene(video_path: str | Path, scene: dict) -> None:
    """Cache scene data for the video path."""
    try:
        _PHASH_SCENE_CACHE[str(Path(video_path).resolve())] = scene
    except Exception:
        pass


def clear_cached_scenes() -> None:
    """Clear all cached scenes."""
    _PHASH_SCENE_CACHE.clear()


FIND_BY_HASH_FULL_QUERY = """
query FindScenesByHash($fingerprints: [[FingerprintQueryInput!]!]!) {
  findScenesBySceneFingerprints(fingerprints: $fingerprints) {
    id
    title
    code
    details
    director
    date
    duration
    urls {
      url
    }
    images {
      url
    }
    studio {
      name
    }
    tags {
      name
    }
    performers {
      as
      performer {
        name
        gender
        images {
          url
        }
      }
    }
  }
}
"""


async def resolve_number_by_phash(
    video_path: str | Path,
    api_key: str = "",
    base_url: str = "https://javstash.org",
    proxy: str = "",
    endpoints: list[dict[str, str]] | None = None,
) -> str | None:
    """Resolve the video's official code/number using pHash/OSHASH via JavStash and StashDB.

    Priority:
    1. Endpoint priority: JavStash first, then StashDB.
    2. Hash priority: PHASH first, then OSHASH.

    If a matching scene is found, caches the full scene data in _PHASH_SCENE_CACHE for the crawler,
    and returns the code (or title).
    """
    path = Path(video_path)
    if not path.is_file():
        return None

    # Normalise endpoints list
    target_endpoints = list(endpoints) if endpoints else []
    if not target_endpoints and api_key:
        target_endpoints.append(
            {
                "name": "JavStash",
                "url": base_url,
                "api_key": api_key,
            }
        )

    if not target_endpoints:
        return None

    start_time = time.time()

    # Check cache first
    cached = get_cached_scene(path)
    if cached:
        code = cached.get("code") or cached.get("title")
        if code:
            code_str = str(code).strip()
            elapsed = time.time() - start_time
            LogBuffer.log().write(f"\n 💡 [pHash识别] 命中本地指纹缓存番号: {code_str} (耗时 {elapsed:.2f}s)")
            return code_str

    endpoint_names = " / ".join(ep.get("name", "Stash") for ep in target_endpoints)
    LogBuffer.log().write(f"\n 🔍 [pHash识别] 正在提取视频指纹并检索 {endpoint_names}...")

    # 1. Compute PHASH (perceptual hash across 25 frames)
    phash_val = compute_video_phash(path)

    # 2. Compute OSHASH (OpenSubtitles hash)
    oshash_val = None
    try:
        import oshash

        oshash_val = oshash.oshash(str(path))
    except Exception as e:
        logger.debug(f"计算 OSHASH 失败: {e}")

    if not phash_val and not oshash_val:
        elapsed = time.time() - start_time
        LogBuffer.log().write(
            f"\n 🟡 [pHash识别] 未能生成有效视频指纹(pHash/OSHASH)，回退常规识别 (耗时 {elapsed:.2f}s)"
        )
        return None

    # Build batch query fingerprints: group 0 is PHASH, group 1 is OSHASH (or 0 if no phash)
    fingerprints: list[list[dict[str, str]]] = []
    has_phash = bool(phash_val)
    if phash_val:
        fingerprints.append([{"algorithm": "PHASH", "hash": phash_val}])
    if oshash_val:
        fingerprints.append([{"algorithm": "OSHASH", "hash": oshash_val}])

    client_kwargs: dict = {"timeout": 15.0, "verify": False}
    if proxy:
        client_kwargs["proxy"] = proxy

    try:
        import httpx

        async with httpx.AsyncClient(**client_kwargs) as client:
            for ep in target_endpoints:
                ep_name = ep.get("name", "Stash")
                ep_url = ep.get("url", "").rstrip("/") + "/graphql"
                ep_key = ep.get("api_key", "").strip()

                if not ep_key or not ep_url:
                    continue

                headers = {
                    "Content-Type": "application/json",
                    "ApiKey": ep_key,
                    "User-Agent": "MDCx/2.0",
                    "Accept": "application/json",
                }

                try:
                    res = await client.post(
                        ep_url,
                        json={"query": FIND_BY_HASH_FULL_QUERY, "variables": {"fingerprints": fingerprints}},
                        headers=headers,
                    )
                    if res.status_code != 200:
                        logger.warning(f"{ep_name} 指纹查询网络异常 HTTP {res.status_code}")
                        continue

                    data = res.json().get("data", {})
                    nested = data.get("findScenesBySceneFingerprints", [])
                    if not isinstance(nested, list) or not nested:
                        continue

                    matched_scene = None
                    matched_algo = ""

                    # Priority 1: PHASH match
                    if has_phash and len(nested) > 0 and nested[0] and isinstance(nested[0], list):
                        matched_scene = nested[0][0]
                        matched_algo = "PHASH"

                    # Priority 2: OSHASH match
                    osh_idx = 1 if has_phash else 0
                    if (
                        not matched_scene
                        and oshash_val
                        and len(nested) > osh_idx
                        and nested[osh_idx]
                        and isinstance(nested[osh_idx], list)
                    ):
                        matched_scene = nested[osh_idx][0]
                        matched_algo = "OSHASH"

                    if matched_scene:
                        set_cached_scene(path, matched_scene)
                        code = matched_scene.get("code") or matched_scene.get("title")
                        if code:
                            code_str = str(code).strip()
                            elapsed = time.time() - start_time
                            LogBuffer.log().write(
                                f"\n 💡 [pHash识别] 命中 {ep_name} [{matched_algo}] 真实番号: {code_str} (耗时 {elapsed:.2f}s)"
                            )
                            return code_str

                except Exception as ep_err:
                    logger.warning(f"{ep_name} 指纹检索异常: {ep_err}")
                    continue

        elapsed = time.time() - start_time
        LogBuffer.log().write(
            f"\n 🟡 [pHash识别] 视频指纹在 {endpoint_names} 中均未收录，回退文件名/正则识别 (耗时 {elapsed:.2f}s)"
        )
    except Exception as e:
        elapsed = time.time() - start_time
        logger.warning(f"通过视频指纹识别番号异常: {e}")
        LogBuffer.log().write(f"\n ⚠️ [pHash识别] 异常: {e}，回退常规正则 (耗时 {elapsed:.2f}s)")
        return None

    return None
